### ISSUE TITLE
ipv6 link-local address with %interface name are not handled

### ISSUE THREAD

**Issue by buzzdeee** [thrnio/puppet-ip#1]
Hi,

since not long ago, https://github.com/xaque208/puppet-bsd uses your module to check for types.
On one of my nodes I specify its default route as `fe80::1%re0`
That is a link local address, suffixed with %interface name (re0 is the interface in question), so the node knows, which interface to use to communicate with the world.

cheers,
Sebastian

**Comment by ghoneycutt** [comment]
This module is no longer maintained. Its functionality has been incorporated in https://github.com/puppetlabs/puppetlabs-stdlib as of version 4.25.0. If this is still an issue, please target that code base.
